spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=PRC&useSSL=false
    username: root
    password: 123456

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    #operations-sorter: order
  api-docs:
    path: /v3/api-docs
    enabled: true
  group-configs:
    - group: 'default'
      display-name: '测试'
      paths-to-match: '/**'
      packages-to-scan: com.kline
  default-flat-param-object: true

knife4j:
  enable: true
  setting:
    enable-swagger-models: true  # 必须为 true
    swagger-model-name: 实体类列表